# Generated by Django 4.1.1 on 2022-09-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nomes')),
                ('sobrenome', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('funcao', models.CharField(choices=[('Contador', 'CONTADOR'), ('Administrador', 'ADMINISTRADOR'), ('Economista', 'ECONOMISTA'), ('Outros', 'OUTRO')], max_length=13, verbose_name='Funções')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['-nome', 'sobrenome'],
            },
        ),
    ]
